spring.application.name=ProjetAdresse2emeEssai


# Active/Désactive le lancement automatique du job au démarrage
spring.batch.job.enabled=true

# Initialise automatiquement le schéma de métadonnées Spring Batch
spring.batch.jdbc.initialize-schema=always

# Init
spring.jpa.defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

# Datasource SQLite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:db.sqlite

# Logging SQL
logging.level.org.springframework.batch=DEBUG

batch.input.file=src/main/resources/adresses-79.csv